export ZSH=$HOME/.oh-my-zsh
export DOTFILES=$HOME/dotfiles
export EDITOR='vim'

ZSH_THEME="refined"
KEYTIMEOUT=1

source ~/.aliases

export PATH=""
export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/bin"
export PATH="$PATH:/bin"
export PATH="$PATH:/usr/sbin"
export PATH="$PATH:/sbin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$DOTFILES/bin"
export PATH="$PATH:/usr/local/sbin"
export PATH="$PATH:/usr/local/share/dotnet"
export PATH="$PATH:$HOME/.dotnet/tools"

export MESA_LOADER_DRIVER_OVERRIDE=i965

source $ZSH/oh-my-zsh.sh
export PATH="$PATH:$HOME/.yarn/bin"
export TERM=xterm-256color

BASE16_SHELL=$HOME/.base16-manager/chriskempson/base16-shell
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

base16-manager set eighties
clear
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -f -u -g ""'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export PATH="$PATH:$HOME/.rbenv/bin"

eval "$(rbenv init -)"
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

export MGFXC_WINE_PATH=/Users/georgeallen/.winemonogame
