export ZSH=$HOME/.oh-my-zsh
export DOTFILES=$HOME/dotfiles
export ZSH_CUSTOM=$DOTFILES/zsh/zsh_custom
export EDITOR='vim'

export GOPATH=$HOME/Developer

export TERM=xterm-256color
export DOCKERID=gallen93

PATH=""
PATH="$PATH:/usr/local/bin"
PATH="$PATH:/usr/bin"
PATH="$PATH:/bin"
PATH="$PATH:/usr/sbin"
PATH="$PATH:/sbin"
PATH="$PATH:`yarn global bin`"
PATH="$PATH:$(go env GOPATH)/bin"
PATH="$PATH:$HOME/.rbenv/bin"
PATH="$PATH:$HOME/.rbenv/shims"
PATH="$PATH:$HOME/.cargo/bin"
PATH="$PATH:$DOTFILES/bin"
export PATH

ZSH_THEME="refined"

plugins=(git, bundler, brew, gem)

source $ZSH/oh-my-zsh.sh

source ~/.aliases
[ -f ~/.private-env ] && source ~/.private-env

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval "$(rbenv init -)"
