eval "$(rbenv init -)"

export ZSH=$HOME/.oh-my-zsh
export EDITOR='vim'

export GOPATH=$HOME/Developer

PATH=""
PATH="$PATH:/usr/local/bin"
PATH="$PATH:/usr/bin"
PATH="$PATH:/bin"
PATH="$PATH:/usr/sbin"
PATH="$PATH:/sbin"
PATH="$PATH:`yarn global bin`"
PATH=$PATH:$(go env GOPATH)/bin
export PATH

ZSH_THEME="dallas"

plugins=(git, bundler, brew, gem)

source $ZSH/oh-my-zsh.sh

source ~/.aliases
[ -f ~/.private-env ] && source ~/.private-env

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
